
        // =========================================================================
        // STUDENT MASTER DATA & ALL STUDENTS DOCUMENTS REGISTRY (HOD / PRINCIPAL / FACULTY)
        // =========================================================================

        const MASTER_DOCS_LIST = [
            { key: 'aadharFront', label: 'Aadhar Card (Front)', icon: '🪪', req: true, desc: 'Government UIDAI Aadhar Front' },
            { key: 'aadharBack', label: 'Aadhar Card (Back)', icon: '🪪', req: true, desc: 'Government UIDAI Aadhar Back' },
            { key: 'tenthMarksheet', label: '10th (SSLC) Mark Sheet', icon: '📜', req: true, desc: 'Official Secondary School Certificate' },
            { key: 'twelfthMarksheet', label: '12th (HSC) / Diploma Marksheet', icon: '📜', req: true, desc: 'Higher Secondary / Diploma Certificate' },
            { key: 'tc', label: 'Transfer Certificate (TC)', icon: '📑', req: true, desc: 'Original Transfer Certificate from Institution' },
            { key: 'community', label: 'Community Certificate', icon: '🏛️', req: true, desc: 'Tahsildar / Revenue Department Issued' },
            { key: 'income', label: 'Income Certificate', icon: '💰', req: true, desc: 'Annual Family Income Certificate' },
            { key: 'nativity', label: 'Nativity Certificate', icon: '📍', req: false, desc: 'Tamil Nadu Nativity Certificate' },
            { key: 'firstGraduate', label: 'First Graduate Certificate', icon: '🎓', req: false, desc: 'Tahsildar Issued FG Certificate' },
            { key: 'studentPhoto', label: 'Student Passport Photo', icon: '📷', req: true, desc: 'Formal Passport Photograph' },
            { key: 'studentSignature', label: 'Student Digital Signature', icon: '✍️', req: true, desc: 'Signature on white paper' },
            { key: 'medical', label: 'Medical Fitness Certificate', icon: '🏥', req: true, desc: 'Certified by Registered Medical Practitioner' },
            { key: 'antiRagging', label: 'Anti-Ragging Undertaking', icon: '🛡️', req: true, desc: 'Signed Student & Parent Undertaking' },
            { key: 'allotmentOrder', label: 'DOTE Allotment Order', icon: '🏛️', req: false, desc: 'TNEA Government Allotment Letter' },
            { key: 'feesReceipt', label: 'College Fees Receipts', icon: '🧾', req: true, desc: 'Recent Term Tuition / Hostel Receipt' },
            { key: 'bankPassbook', label: 'Bank Passbook Front Page', icon: '🏦', req: true, desc: 'Passbook showing A/C No and IFSC' },
            { key: 'achievement', label: 'Achievements / Extracurricular', icon: '🏆', req: false, desc: 'Sports, Technical Symposium or NPTEL' }
        ];

        let currentActiveMasterTab = 'personal';
        let currentModalActiveStudentEmail = null;
        let selectedAllStudentCheckboxes = new Set();

        // Seed initial student master data if not existing
        function initStudentMasterDataStore() {
            let store = {};
            try {
                store = JSON.parse(localStorage.getItem('swce_student_master_data') || '{}');
            } catch (e) {
                store = {};
            }

            const defaultStudents = {
                'student@study-world.edu.in': {
                    email: 'student@study-world.edu.in',
                    studentId: 'SWCE-2024-CSE-067',
                    firstName: 'Sakthi',
                    lastName: 'Madhavan',
                    dob: '2004-06-18',
                    gender: 'Male',
                    bloodGroup: 'O+',
                    aadhar: '723489123067',
                    mobile: '9123456780',
                    altMobile: '9876543210',
                    photo: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
                    community: 'BC',
                    religion: 'Hindu',
                    motherTongue: 'Tamil',
                    nationality: 'Indian',
                    district: 'Coimbatore',
                    state: 'Tamil Nadu',
                    pincode: '641105',
                    addressPerm: '42, Kurinji Nagar, Madukkarai, Coimbatore - 641105',
                    addressCurr: 'SWCE Campus Hostel, Room 204-B, Kurinji Block',

                    // Academic
                    dept: 'CSE',
                    year: 'III',
                    semester: '6',
                    batch: '2024-2028',
                    admType: 'GQ',
                    admDate: '2024-08-12',
                    tenthSchool: 'Govt Higher Secondary School, Madukkarai',
                    tenthPercent: '93.6%',
                    tenthYear: '2022',
                    tenthBoard: 'Tamil Nadu State Board',
                    twelfthSchool: 'St. Joseph Higher Secondary School, Coimbatore',
                    twelfthPercent: '91.2%',
                    twelfthCutoff: 186.5,
                    cgpa: 8.74,
                    sgpa: 8.85,
                    attendance: 94,

                    // Family
                    fatherName: 'Madhavan R',
                    fatherOcc: 'Agriculture & Business',
                    fatherMobile: '9876543210',
                    fatherIncome: '1,80,000',
                    motherName: 'Lakshmi M',
                    motherOcc: 'Homemaker',
                    motherMobile: '9876543211',
                    motherIncome: '0',
                    guardianName: 'Sundaram R (Uncle)',
                    guardianRel: 'Uncle',
                    guardianMobile: '9876543212',
                    emergencyContact: 'Madhavan R (Father)',
                    emergencyMobile: '9876543210',
                    familyIncome: '1,80,000',
                    siblingsCount: 1,
                    firstGraduate: 'No',

                    // Fees
                    feeTotal: 133500,
                    feePaid: 90000,
                    feeRemaining: 43500,
                    scholarshipType: 'BC/MBC Welfare',
                    scholarshipAmount: '12,500',
                    scholarshipId: 'BCW-TN-2026-7812',
                    feeRemarks: 'Tuition paid in 2 installments. Hostel due on 15 Oct.',

                    // Hostel
                    accommodation: 'Hosteller',
                    hostelBlock: 'Kurinji Boys Block A',
                    roomNo: '204-B',
                    messType: 'Non-Veg',
                    transportMode: 'Hostel Walk',
                    busRoute: 'N/A',
                    busStop: 'Campus',
                    vehicleNo: 'N/A',

                    // Bank
                    bankName: 'State Bank of India (SBI)',
                    accountHolder: 'Sakthi Madhavan',
                    accountNo: '384910294821',
                    ifsc: 'SBIN0001429',
                    bankBranch: 'Madukkarai Branch, Coimbatore',
                    micr: '641002014',

                    // Official
                    admissionNo: 'SWCE/ADM/2024/067',
                    rollNo: '721124243067',
                    regNo: '721124243067',
                    quota: 'Government Quota (TNEA)',
                    mentorName: 'Dr. P. Senthil Kumar (HOD CSE)',
                    mentorEmail: 'hod.cse@study-world.edu.in',
                    verifiedByHOD: true,
                    locked: true,
                    verifiedDate: '15-09-2026 11:30 AM',
                    hodRemarks: 'All original certificates verified in person. Academic records validated.',
                    lastUpdated: Date.now() - 3600000,

                    // Documents
                    documents: {
                        aadharFront: { fileName: 'Aadhar_Front_Sakthi.pdf', size: '340 KB', uploadedAt: '12-09-2026', verified: true, status: 'Verified' },
                        aadharBack: { fileName: 'Aadhar_Back_Sakthi.pdf', size: '280 KB', uploadedAt: '12-09-2026', verified: true, status: 'Verified' },
                        tenthMarksheet: { fileName: '10th_MarkSheet_721124243067.pdf', size: '512 KB', uploadedAt: '12-09-2026', verified: true, status: 'Verified' },
                        twelfthMarksheet: { fileName: '12th_MarkSheet_721124243067.pdf', size: '540 KB', uploadedAt: '12-09-2026', verified: true, status: 'Verified' },
                        tc: { fileName: 'Transfer_Certificate_Original.pdf', size: '420 KB', uploadedAt: '12-09-2026', verified: true, status: 'Verified' },
                        community: { fileName: 'Community_Certificate_BC.pdf', size: '310 KB', uploadedAt: '12-09-2026', verified: true, status: 'Verified' },
                        income: { fileName: 'Income_Certificate_2026.pdf', size: '290 KB', uploadedAt: '12-09-2026', verified: true, status: 'Verified' },
                        studentPhoto: { fileName: 'Formal_Photo_Sakthi.jpg', size: '180 KB', uploadedAt: '12-09-2026', verified: true, status: 'Verified' },
                        studentSignature: { fileName: 'Signature_Digital.png', size: '65 KB', uploadedAt: '12-09-2026', verified: true, status: 'Verified' },
                        medical: { fileName: 'Medical_Fitness_Cert.pdf', size: '390 KB', uploadedAt: '13-09-2026', verified: true, status: 'Verified' },
                        antiRagging: { fileName: 'Anti_Ragging_Affidavit.pdf', size: '250 KB', uploadedAt: '13-09-2026', verified: true, status: 'Verified' },
                        allotmentOrder: { fileName: 'TNEA_Allotment_Order.pdf', size: '480 KB', uploadedAt: '13-09-2026', verified: true, status: 'Verified' },
                        feesReceipt: { fileName: 'SWCE_Fees_Receipt_Term1.pdf', size: '210 KB', uploadedAt: '14-09-2026', verified: true, status: 'Verified' },
                        bankPassbook: { fileName: 'SBI_Passbook_Front.pdf', size: '350 KB', uploadedAt: '14-09-2026', verified: true, status: 'Verified' }
                    }
                },
                'student_001@study-world.edu.in': {
                    email: 'student_001@study-world.edu.in',
                    studentId: 'SWCE-2024-CSE-054',
                    firstName: 'Priya',
                    lastName: 'Raman',
                    dob: '2004-09-22',
                    gender: 'Female',
                    bloodGroup: 'B+',
                    aadhar: '541278964054',
                    mobile: '9845012345',
                    altMobile: '9789012345',
                    photo: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&auto=format&fit=crop&q=80',
                    community: 'MBC',
                    religion: 'Hindu',
                    motherTongue: 'Tamil',
                    nationality: 'Indian',
                    district: 'Tirupur',
                    state: 'Tamil Nadu',
                    pincode: '641601',
                    addressPerm: '18, Gandhi Street, Tirupur - 641601',
                    addressCurr: 'SWCE Girls Hostel, Marutham Block, Room 108',

                    dept: 'CSE',
                    year: 'III',
                    semester: '6',
                    batch: '2024-2028',
                    admType: 'GQ',
                    admDate: '2024-08-14',
                    tenthSchool: 'Kongu Vellalar Matriculation School, Tirupur',
                    tenthPercent: '95.0%',
                    tenthYear: '2022',
                    tenthBoard: 'Tamil Nadu State Board',
                    twelfthSchool: 'Vidyalaya Girls Higher Secondary School',
                    twelfthPercent: '93.5%',
                    twelfthCutoff: 189.0,
                    cgpa: 9.12,
                    sgpa: 9.20,
                    attendance: 96,

                    fatherName: 'Raman K',
                    fatherOcc: 'Textile Export Manager',
                    fatherMobile: '9845012344',
                    fatherIncome: '2,50,000',
                    motherName: 'Shanthi R',
                    motherOcc: 'Teacher',
                    motherMobile: '9845012346',
                    motherIncome: '1,20,000',
                    guardianName: 'N/A',
                    guardianRel: 'N/A',
                    guardianMobile: '',
                    emergencyContact: 'Raman K (Father)',
                    emergencyMobile: '9845012344',
                    familyIncome: '3,70,000',
                    siblingsCount: 1,
                    firstGraduate: 'Yes',

                    feeTotal: 125000,
                    feePaid: 125000,
                    feeRemaining: 0,
                    scholarshipType: 'First Graduate',
                    scholarshipAmount: '25,000',
                    scholarshipId: 'FG-TN-2024-5120',
                    feeRemarks: 'Complete annual fee cleared.',

                    accommodation: 'Hosteller',
                    hostelBlock: 'Marutham Girls Block',
                    roomNo: '108-A',
                    messType: 'Veg',
                    transportMode: 'Hostel Walk',
                    busRoute: 'N/A',
                    busStop: 'Campus',
                    vehicleNo: 'N/A',

                    bankName: 'Canara Bank',
                    accountHolder: 'Priya Raman',
                    accountNo: '102938475612',
                    ifsc: 'CNRB0002140',
                    bankBranch: 'Tirupur Main Branch',
                    micr: '641015002',

                    admissionNo: 'SWCE/ADM/2024/054',
                    rollNo: '721124243054',
                    regNo: '721124243054',
                    quota: 'Government Quota (TNEA)',
                    mentorName: 'Mrs. S. Meenakshi (AP / CSE)',
                    mentorEmail: 'meenakshi.cse@study-world.edu.in',
                    verifiedByHOD: true,
                    locked: true,
                    verifiedDate: '16-09-2026 02:15 PM',
                    hodRemarks: 'Documents verified and approved. First Graduate subsidy validated.',
                    lastUpdated: Date.now() - 7200000,

                    documents: {
                        aadharFront: { fileName: 'Aadhar_Front_Priya.pdf', size: '290 KB', uploadedAt: '10-09-2026', verified: true, status: 'Verified' },
                        aadharBack: { fileName: 'Aadhar_Back_Priya.pdf', size: '270 KB', uploadedAt: '10-09-2026', verified: true, status: 'Verified' },
                        tenthMarksheet: { fileName: '10th_MarkSheet_Priya.pdf', size: '480 KB', uploadedAt: '10-09-2026', verified: true, status: 'Verified' },
                        twelfthMarksheet: { fileName: '12th_MarkSheet_Priya.pdf', size: '520 KB', uploadedAt: '10-09-2026', verified: true, status: 'Verified' },
                        tc: { fileName: 'Transfer_Certificate_Priya.pdf', size: '390 KB', uploadedAt: '10-09-2026', verified: true, status: 'Verified' },
                        community: { fileName: 'Community_Cert_MBC.pdf', size: '320 KB', uploadedAt: '10-09-2026', verified: true, status: 'Verified' },
                        firstGraduate: { fileName: 'First_Graduate_Certificate_Govt.pdf', size: '410 KB', uploadedAt: '11-09-2026', verified: true, status: 'Verified' },
                        studentPhoto: { fileName: 'Passport_Photo_Priya.jpg', size: '160 KB', uploadedAt: '10-09-2026', verified: true, status: 'Verified' },
                        studentSignature: { fileName: 'Signature_Priya.png', size: '50 KB', uploadedAt: '10-09-2026', verified: true, status: 'Verified' },
                        bankPassbook: { fileName: 'Canara_Passbook.pdf', size: '330 KB', uploadedAt: '11-09-2026', verified: true, status: 'Verified' }
                    }
                },
                'kavitha.mech@study-world.edu.in': {
                    email: 'kavitha.mech@study-world.edu.in',
                    studentId: 'SWCE-2023-MECH-022',
                    firstName: 'Kavitha',
                    lastName: 'Sundaram',
                    dob: '2003-11-05',
                    gender: 'Female',
                    bloodGroup: 'A+',
                    aadhar: '652391024022',
                    mobile: '9789123450',
                    altMobile: '9843012345',
                    photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80',
                    community: 'SC',
                    religion: 'Hindu',
                    motherTongue: 'Tamil',
                    nationality: 'Indian',
                    district: 'Salem',
                    state: 'Tamil Nadu',
                    pincode: '636001',
                    addressPerm: '102, Salem Main Road, Omalur, Salem',
                    addressCurr: 'Room 312, Marutham Block, SWCE Hostel',

                    dept: 'MECH',
                    year: 'IV',
                    semester: '8',
                    batch: '2023-2027',
                    admType: 'GQ',
                    admDate: '2023-08-10',
                    tenthSchool: 'Govt Model Higher Secondary School, Salem',
                    tenthPercent: '91.0%',
                    tenthYear: '2021',
                    tenthBoard: 'Tamil Nadu State Board',
                    twelfthSchool: 'Govt Model Higher Secondary School, Salem',
                    twelfthPercent: '88.5%',
                    twelfthCutoff: 178.0,
                    cgpa: 8.42,
                    sgpa: 8.50,
                    attendance: 92,

                    fatherName: 'Sundaram P',
                    fatherOcc: 'Govt Employee',
                    fatherMobile: '9843012345',
                    fatherIncome: '1,40,000',
                    motherName: 'Kala S',
                    motherOcc: 'Homemaker',
                    motherMobile: '',
                    motherIncome: '0',
                    guardianName: '',
                    guardianRel: '',
                    guardianMobile: '',
                    emergencyContact: 'Sundaram P (Father)',
                    emergencyMobile: '9843012345',
                    familyIncome: '1,40,000',
                    siblingsCount: 2,
                    firstGraduate: 'No',

                    feeTotal: 110000,
                    feePaid: 110000,
                    feeRemaining: 0,
                    scholarshipType: 'Post-Matric SC/ST',
                    scholarshipAmount: '55,000',
                    scholarshipId: 'PMS-TN-2023-8891',
                    feeRemarks: 'Full tuition funded by Post-Matric Welfare.',

                    accommodation: 'Hosteller',
                    hostelBlock: 'Marutham Girls Block',
                    roomNo: '312-B',
                    messType: 'Non-Veg',
                    transportMode: 'Hostel Walk',
                    busRoute: 'N/A',
                    busStop: 'Campus',
                    vehicleNo: 'N/A',

                    bankName: 'Indian Overseas Bank (IOB)',
                    accountHolder: 'Kavitha Sundaram',
                    accountNo: '23450100003412',
                    ifsc: 'IOBA0000512',
                    bankBranch: 'Salem Town Branch',
                    micr: '636020005',

                    admissionNo: 'SWCE/ADM/2023/022',
                    rollNo: '721123114022',
                    regNo: '721123114022',
                    quota: 'Government Quota (TNEA)',
                    mentorName: 'Dr. K. Rajasekaran (Prof / MECH)',
                    mentorEmail: 'rajasekaran.mech@study-world.edu.in',
                    verifiedByHOD: true,
                    locked: true,
                    verifiedDate: '10-09-2026 10:00 AM',
                    hodRemarks: 'Final year records verified. Project and placement clearances active.',
                    lastUpdated: Date.now() - 14400000,

                    documents: {
                        aadharFront: { fileName: 'Aadhar_Kavitha.pdf', size: '310 KB', uploadedAt: '05-09-2026', verified: true, status: 'Verified' },
                        tenthMarksheet: { fileName: '10th_Cert_Kavitha.pdf', size: '440 KB', uploadedAt: '05-09-2026', verified: true, status: 'Verified' },
                        twelfthMarksheet: { fileName: '12th_Cert_Kavitha.pdf', size: '460 KB', uploadedAt: '05-09-2026', verified: true, status: 'Verified' },
                        community: { fileName: 'SC_Community_Cert.pdf', size: '300 KB', uploadedAt: '05-09-2026', verified: true, status: 'Verified' },
                        income: { fileName: 'Income_Cert_Salem.pdf', size: '280 KB', uploadedAt: '05-09-2026', verified: true, status: 'Verified' },
                        bankPassbook: { fileName: 'IOB_Passbook.pdf', size: '320 KB', uploadedAt: '06-09-2026', verified: true, status: 'Verified' }
                    }
                },
                'arun.ece@study-world.edu.in': {
                    email: 'arun.ece@study-world.edu.in',
                    studentId: 'SWCE-2025-ECE-019',
                    firstName: 'Arun',
                    lastName: 'Kumar',
                    dob: '2005-03-12',
                    gender: 'Male',
                    bloodGroup: 'AB+',
                    aadhar: '481239014019',
                    mobile: '9655012345',
                    altMobile: '9443012345',
                    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
                    community: 'BC',
                    religion: 'Hindu',
                    motherTongue: 'Tamil',
                    nationality: 'Indian',
                    district: 'Coimbatore',
                    state: 'Tamil Nadu',
                    pincode: '641012',
                    addressPerm: '74, Cross Cut Road, Gandhipuram, Coimbatore',
                    addressCurr: '74, Cross Cut Road, Gandhipuram, Coimbatore',

                    dept: 'ECE',
                    year: 'II',
                    semester: '4',
                    batch: '2025-2029',
                    admType: 'MQ',
                    admDate: '2025-08-18',
                    tenthSchool: 'Suburban Matriculation Higher Secondary School',
                    tenthPercent: '88.2%',
                    tenthYear: '2023',
                    tenthBoard: 'Tamil Nadu State Board',
                    twelfthSchool: 'Suburban Higher Secondary School',
                    twelfthPercent: '86.0%',
                    twelfthCutoff: 172.5,
                    cgpa: 7.95,
                    sgpa: 8.10,
                    attendance: 89,

                    fatherName: 'Kumar V',
                    fatherOcc: 'Retail Merchant',
                    fatherMobile: '9443012345',
                    fatherIncome: '3,00,000',
                    motherName: 'Geetha K',
                    motherOcc: 'Homemaker',
                    motherMobile: '',
                    motherIncome: '0',
                    guardianName: '',
                    guardianRel: '',
                    guardianMobile: '',
                    emergencyContact: 'Kumar V (Father)',
                    emergencyMobile: '9443012345',
                    familyIncome: '3,00,000',
                    siblingsCount: 1,
                    firstGraduate: 'No',

                    feeTotal: 130000,
                    feePaid: 105000,
                    feeRemaining: 25000,
                    scholarshipType: 'None',
                    scholarshipAmount: '0',
                    scholarshipId: 'N/A',
                    feeRemarks: 'Term 2 balance ₹25,000 pending.',

                    accommodation: 'Day Scholar',
                    hostelBlock: 'N/A',
                    roomNo: 'N/A',
                    messType: 'N/A',
                    transportMode: 'College Bus',
                    busRoute: 'Route 14 - Gandhipuram',
                    busStop: 'Gandhipuram Bus Stand',
                    vehicleNo: 'TN-38-SWCE-014',

                    bankName: 'HDFC Bank',
                    accountHolder: 'Arun Kumar',
                    accountNo: '50100234567890',
                    ifsc: 'HDFC0000219',
                    bankBranch: 'Gandhipuram Branch',
                    micr: '641240003',

                    admissionNo: 'SWCE/ADM/2025/019',
                    rollNo: '721125106019',
                    regNo: '721125106019',
                    quota: 'Management Quota',
                    mentorName: 'Dr. G. Manikandan (AP / ECE)',
                    mentorEmail: 'manikandan.ece@study-world.edu.in',
                    verifiedByHOD: false,
                    locked: false,
                    verifiedDate: 'Pending Review',
                    hodRemarks: 'Pending original TC verification from earlier college.',
                    lastUpdated: Date.now() - 18000000,

                    documents: {
                        aadharFront: { fileName: 'Aadhar_Arun.pdf', size: '280 KB', uploadedAt: '08-09-2026', verified: true, status: 'Verified' },
                        tenthMarksheet: { fileName: '10th_Arun.pdf', size: '420 KB', uploadedAt: '08-09-2026', verified: true, status: 'Verified' },
                        twelfthMarksheet: { fileName: '12th_Arun.pdf', size: '450 KB', uploadedAt: '08-09-2026', verified: false, status: 'Pending' },
                        studentPhoto: { fileName: 'Photo_Arun.jpg', size: '150 KB', uploadedAt: '08-09-2026', verified: true, status: 'Verified' }
                    }
                },
                'divya.ai@study-world.edu.in': {
                    email: 'divya.ai@study-world.edu.in',
                    studentId: 'SWCE-2026-AIDS-031',
                    firstName: 'Divya',
                    lastName: 'Balaji',
                    dob: '2006-04-19',
                    gender: 'Female',
                    bloodGroup: 'O-',
                    aadhar: '891234567031',
                    mobile: '9843912345',
                    altMobile: '9488012345',
                    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
                    community: 'OC',
                    religion: 'Hindu',
                    motherTongue: 'Telugu',
                    nationality: 'Indian',
                    district: 'Coimbatore',
                    state: 'Tamil Nadu',
                    pincode: '641004',
                    addressPerm: '12, Sri Ram Layout, Peelamedu, Coimbatore',
                    addressCurr: '12, Sri Ram Layout, Peelamedu, Coimbatore',

                    dept: 'AIDS',
                    year: 'I',
                    semester: '2',
                    batch: '2026-2030',
                    admType: 'GQ',
                    admDate: '2026-08-20',
                    tenthSchool: 'GRG Matriculation Higher Secondary School',
                    tenthPercent: '96.5%',
                    tenthYear: '2024',
                    tenthBoard: 'Tamil Nadu State Board',
                    twelfthSchool: 'GRG Higher Secondary School',
                    twelfthPercent: '94.8%',
                    twelfthCutoff: 192.5,
                    cgpa: 9.35,
                    sgpa: 9.40,
                    attendance: 98,

                    fatherName: 'Balaji V',
                    fatherOcc: 'Software Architect',
                    fatherMobile: '9488012345',
                    fatherIncome: '8,50,000',
                    motherName: 'Radha B',
                    motherOcc: 'Bank Officer',
                    motherMobile: '9488012346',
                    motherIncome: '6,20,000',
                    guardianName: '',
                    guardianRel: '',
                    guardianMobile: '',
                    emergencyContact: 'Balaji V (Father)',
                    emergencyMobile: '9488012345',
                    familyIncome: '14,70,000',
                    siblingsCount: 1,
                    firstGraduate: 'No',

                    feeTotal: 135000,
                    feePaid: 135000,
                    feeRemaining: 0,
                    scholarshipType: 'Institutional Merit',
                    scholarshipAmount: '15,000',
                    scholarshipId: 'MERIT-SWCE-2026-004',
                    feeRemarks: 'Full academic fee cleared on admission.',

                    accommodation: 'Day Scholar',
                    hostelBlock: 'N/A',
                    roomNo: 'N/A',
                    messType: 'N/A',
                    transportMode: 'Two Wheeler',
                    busRoute: 'N/A',
                    busStop: 'Peelamedu',
                    vehicleNo: 'TN-38-BZ-4412',

                    bankName: 'Axis Bank',
                    accountHolder: 'Divya Balaji',
                    accountNo: '921010045612345',
                    ifsc: 'UTIB0000088',
                    bankBranch: 'Peelamedu Branch',
                    micr: '641211002',

                    admissionNo: 'SWCE/ADM/2026/031',
                    rollNo: '721126244031',
                    regNo: '721126244031',
                    quota: 'Government Quota (TNEA)',
                    mentorName: 'Mrs. N. Kavithamani (AP / AIDS)',
                    mentorEmail: 'kavithamani.aids@study-world.edu.in',
                    verifiedByHOD: false,
                    locked: false,
                    verifiedDate: 'Pending Review',
                    hodRemarks: '1st Year enrollment documents submitted. Inward verification scheduled.',
                    lastUpdated: Date.now() - 25000000,

                    documents: {
                        aadharFront: { fileName: 'Aadhar_Divya.pdf', size: '310 KB', uploadedAt: '01-09-2026', verified: true, status: 'Verified' },
                        tenthMarksheet: { fileName: '10th_Divya.pdf', size: '510 KB', uploadedAt: '01-09-2026', verified: true, status: 'Verified' },
                        twelfthMarksheet: { fileName: '12th_Divya.pdf', size: '530 KB', uploadedAt: '01-09-2026', verified: true, status: 'Verified' },
                        allotmentOrder: { fileName: 'Allotment_Order_AIDS.pdf', size: '490 KB', uploadedAt: '01-09-2026', verified: true, status: 'Verified' }
                    }
                }
            };

            // Merge default students if not already present
            let modified = false;
            for (const email in defaultStudents) {
                if (!store[email]) {
                    store[email] = defaultStudents[email];
                    modified = true;
                }
            }

            if (modified || Object.keys(store).length === 0) {
                localStorage.setItem('swce_student_master_data', JSON.stringify(store));
            }
        }
