#!/bin/bash
# Quick Start Guide - Digital Leave Letter System

echo "╔═══════════════════════════════════════════════════════════╗"
echo "║   🚀 DIGITAL LEAVE LETTER SYSTEM - QUICK START GUIDE     ║"
echo "║   Study World College of Engineering, Coimbatore         ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""

echo "📋 QUICK START STEPS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "1️⃣  START THE SERVER"
echo "   Command: node server.js"
echo "   Expected: ✅ Server running on http://localhost:5000"
echo ""

echo "2️⃣  OPEN THE APPLICATION"
echo "   Go to: http://localhost:5000 (or open login page directly)"
echo "   File: frontend/login/login.html"
echo ""

echo "3️⃣  LOGIN WITH TEST ACCOUNTS"
echo "   ────────────────────────────────────────"
echo "   Role        | Username      | Password"
echo "   ────────────────────────────────────────"
echo "   Student     | student_001   | student123"
echo "   Faculty     | faculty_001   | faculty123"
echo "   HOD         | hod_001       | hod123"
echo "   Principal   | principal_001 | principal123"
echo "   Admin       | sakthi        | 2006"
echo "   ────────────────────────────────────────"
echo ""

echo "4️⃣  TEST THE WORKFLOW"
echo "   a) Login as student_001"
echo "      → Click 'Apply Leave' tab"
echo "      → Fill dates (2026-05-01 to 2026-05-05)"
echo "      → Click 'Submit' button"
echo ""
echo "   b) Login as faculty_001"
echo "      → Go to 'Pending Leaves' tab"
echo "      → See student's leave request"
echo "      → Click 'Approve' button"
echo "      → Student receives notification"
echo ""

echo "5️⃣  RUN COMPREHENSIVE TESTS"
echo "   Command: node test-suite.js"
echo "   Expected: All 45 tests should PASS (100%)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "📂 KEY FILES & LOCATIONS"
echo ""
echo "Backend:"
echo "  • server.js                    - Main API server"
echo "  • backend/services/NotificationService.js  - Notification engine"
echo "  • backend/config/db.js         - Database connection"
echo ""

echo "Frontend:"
echo "  • frontend/login/login.html           - Login page"
echo "  • frontend/student/dashboard.html     - Student dashboard"
echo "  • frontend/faculty/dashboard.html     - Faculty dashboard"
echo "  • frontend/hod/dashboard.html         - HOD dashboard"
echo "  • frontend/principal/dashboard.html   - Principal dashboard"
echo "  • frontend/admin/dashboard.html       - Admin dashboard"
echo ""

echo "Database:"
echo "  • database/schema.sql          - Create tables"
echo "  • database/seed.sql            - Sample data"
echo ""

echo "Testing:"
echo "  • test-suite.js                - Automated tests"
echo "  • TESTING_GUIDE.md             - Testing documentation"
echo ""

echo "Documentation:"
echo "  • README.md                    - User guide"
echo "  • COMPLETION_REPORT.md         - Project status"
echo "  • LOGIN_SETUP.md               - Authentication setup"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "🎯 FEATURE OVERVIEW"
echo ""
echo "✅ Leave Submission"
echo "   - Students can apply for leave"
echo "   - Notifications sent to faculty"
echo "   - Real-time status tracking"
echo ""

echo "✅ Approval Workflow"
echo "   - Faculty reviews and approves/rejects"
echo "   - HOD makes department-level decisions"
echo "   - Principal gives final approval"
echo "   - Admin oversees entire system"
echo ""

echo "✅ Notifications"
echo "   - In-app notifications with badges"
echo "   - Email notifications on actions"
echo "   - Real-time updates every 30 seconds"
echo ""

echo "✅ Analytics & Reports"
echo "   - Leave statistics by status"
echo "   - Approval rate tracking"
echo "   - Department-wise breakdown"
echo "   - Activity log audit trail"
echo ""

echo "✅ Role-Based Access"
echo "   - Student: Apply and track leaves"
echo "   - Faculty: Review and approve"
echo "   - HOD: Department oversight"
echo "   - Principal: College-wide authority"
echo "   - Admin: System management"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "🔧 TROUBLESHOOTING"
echo ""

echo "Problem: Server won't start"
echo "Solution:"
echo "  • Check if port 5000 is already in use"
echo "  • Verify Node.js is installed: node --version"
echo "  • Check database connection in server.js"
echo ""

echo "Problem: Can't login"
echo "Solution:"
echo "  • Verify test users exist in database"
echo "  • Check if database is running"
echo "  • Review server logs for errors"
echo ""

echo "Problem: No notifications"
echo "Solution:"
echo "  • Check if NotificationService is loaded"
echo "  • Verify database tables exist"
echo "  • Check browser console for errors"
echo ""

echo "Problem: Tests failing"
echo "Solution:"
echo "  • Ensure server is running first"
echo "  • Verify test users exist"
echo "  • Check database connectivity"
echo "  • Run: npm install (to ensure dependencies)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "📞 SUPPORT & DOCUMENTATION"
echo ""
echo "For detailed information:"
echo "  • Read: README.md (User guide)"
echo "  • Read: TESTING_GUIDE.md (Testing procedures)"
echo "  • Read: COMPLETION_REPORT.md (Project status)"
echo "  • Check: Server logs for errors"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "✅ YOU'RE ALL SET!"
echo ""
echo "Next steps:"
echo "  1. Start server: node server.js"
echo "  2. Open login page: frontend/login/login.html"
echo "  3. Test with student_001 / student123"
echo "  4. Run tests: node test-suite.js"
echo ""
echo "Questions? Check the documentation files!"
echo ""
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║               🎓 Happy Learning! 🎓                       ║"
echo "╚═══════════════════════════════════════════════════════════╝"
