// =========================================================================
// STUDY WORLD COLLEGE OF ENGINEERING - STUDENT MASTER DATA BACKEND MODULE
// =========================================================================

const INITIAL_MASTER_STUDENTS = {
  'student@study-world.edu.in': {
    email: 'student@study-world.edu.in',
    studentId: 'SWCE-2024-CSE-067',
    firstName: 'Sakthi',
    lastName: 'Madhavan',
    dob: '2004-06-18',
    gender: 'Male',
    bloodGroup: 'O+',
    aadhar: '723489123067',
    mobile: '9123456780',
    altMobile: '9876543210',
    photo: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
    community: 'BC',
    religion: 'Hindu',
    motherTongue: 'Tamil',
    nationality: 'Indian',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    pincode: '641105',
    addressPerm: '42, Kurinji Nagar, Madukkarai, Coimbatore - 641105',
    addressCurr: 'SWCE Campus Hostel, Room 204-B, Kurinji Block',

    dept: 'CSE',
    year: 'III',
    semester: '6',
    batch: '2024-2028',
    admType: 'GQ',
    admDate: '2024-08-12',
    tenthSchool: 'Govt Higher Secondary School, Madukkarai',
    tenthPercent: '93.6%',
    tenthYear: '2022',
    tenthBoard: 'Tamil Nadu State Board',
    twelfthSchool: 'St. Joseph Higher Secondary School, Coimbatore',
    twelfthPercent: '91.2%',
    twelfthCutoff: 186.5,
    cgpa: 8.74,
    sgpa: 8.85,
    attendance: 94,

    fatherName: 'Madhavan R',
    fatherOcc: 'Agriculture & Business',
    fatherMobile: '9876543210',
    fatherIncome: '1,80,000',
    motherName: 'Lakshmi M',
    motherOcc: 'Homemaker',
    motherMobile: '9876543211',
    motherIncome: '0',
    guardianName: 'Sundaram R',
    guardianRel: 'Uncle',
    guardianMobile: '9876543212',
    emergencyContact: 'Madhavan R (Father)',
    emergencyMobile: '9876543210',
    familyIncome: '1,80,000',
    siblingsCount: 1,
    firstGraduate: 'No',

    feeTotal: 133500,
    feePaid: 90000,
    feeRemaining: 43500,
    scholarshipType: 'BC/MBC Welfare',
    scholarshipAmount: '12,500',
    scholarshipId: 'BCW-TN-2026-7812',
    feeRemarks: 'Tuition verified. Term 2 due in Nov 2026.',

    accommodation: 'Hosteller',
    hostelBlock: 'Kurinji Boys Block A',
    roomNo: '204-B',
    messType: 'Non-Veg',
    transportMode: 'Hostel Walk',
    busRoute: 'N/A',
    busStop: 'Campus',
    vehicleNo: 'N/A',

    bankName: 'State Bank of India (SBI)',
    accountHolder: 'Sakthi Madhavan',
    accountNo: '384910294821',
    ifsc: 'SBIN0001429',
    bankBranch: 'Madukkarai Branch, Coimbatore',
    micr: '641002014',

    admissionNo: 'SWCE/ADM/2024/067',
    rollNo: '721124243067',
    regNo: '721124243067',
    quota: 'Government Quota (TNEA)',
    mentorName: 'Dr. P. Senthil Kumar (HOD CSE)',
    mentorEmail: 'hod.cse@study-world.edu.in',
    verifiedByHOD: true,
    locked: true,
    verifiedDate: '15-09-2026 11:30 AM',
    hodRemarks: 'All academic credentials, government identity, and certificates verified by HOD.',
    lastUpdated: Date.now(),
    documents: {
      aadharFront: { fileName: 'Aadhar_Sakthi_Front.pdf', size: '320 KB', uploadedAt: '12-09-2026', verified: true, status: 'Verified' },
      aadharBack: { fileName: 'Aadhar_Sakthi_Back.pdf', size: '290 KB', uploadedAt: '12-09-2026', verified: true, status: 'Verified' },
      tenthMarksheet: { fileName: '10th_SSLC_Marksheet.pdf', size: '480 KB', uploadedAt: '12-09-2026', verified: true, status: 'Verified' },
      twelfthMarksheet: { fileName: '12th_HSC_Marksheet.pdf', size: '520 KB', uploadedAt: '12-09-2026', verified: true, status: 'Verified' },
      tc: { fileName: 'Transfer_Certificate_Original.pdf', size: '410 KB', uploadedAt: '12-09-2026', verified: true, status: 'Verified' },
      community: { fileName: 'Community_Certificate_BC.pdf', size: '360 KB', uploadedAt: '12-09-2026', verified: true, status: 'Verified' },
      income: { fileName: 'Income_Certificate_2026.pdf', size: '340 KB', uploadedAt: '12-09-2026', verified: true, status: 'Verified' },
      nativity: { fileName: 'Nativity_Certificate_TN.pdf', size: '310 KB', uploadedAt: '12-09-2026', verified: true, status: 'Verified' },
      feesReceipt: { fileName: 'Fee_Receipt_Term1.pdf', size: '280 KB', uploadedAt: '12-09-2026', verified: true, status: 'Verified' },
      bankPassbook: { fileName: 'SBI_Passbook_Front.pdf', size: '440 KB', uploadedAt: '12-09-2026', verified: true, status: 'Verified' },
      studentPhoto: { fileName: 'Student_Passport_Photo.jpg', size: '180 KB', uploadedAt: '12-09-2026', verified: true, status: 'Verified' },
      studentSignature: { fileName: 'Student_Digital_Signature.png', size: '95 KB', uploadedAt: '12-09-2026', verified: true, status: 'Verified' },
      medical: { fileName: 'Medical_Fitness_Certificate.pdf', size: '350 KB', uploadedAt: '12-09-2026', verified: true, status: 'Verified' },
      antiRagging: { fileName: 'Anti_Ragging_Undertaking.pdf', size: '410 KB', uploadedAt: '12-09-2026', verified: true, status: 'Verified' }
    }
  },

  'ananya.s@study-world.edu.in': {
    email: 'ananya.s@study-world.edu.in',
    studentId: 'SWCE-2024-CSE-012',
    firstName: 'Ananya',
    lastName: 'Sridhar',
    dob: '2005-02-14',
    gender: 'Female',
    bloodGroup: 'B+',
    aadhar: '482910394812',
    mobile: '9840123456',
    altMobile: '9840123457',
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    community: 'OC',
    religion: 'Hindu',
    motherTongue: 'Tamil',
    nationality: 'Indian',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    pincode: '641018',
    addressPerm: '18/4, Race Course Road, Coimbatore - 641018',
    addressCurr: '18/4, Race Course Road, Coimbatore - 641018',
    dept: 'CSE',
    year: 'II',
    semester: '4',
    batch: '2024-2028',
    admType: 'GQ',
    admDate: '2024-08-10',
    tenthSchool: 'Bhavans Vidya Mandir, Coimbatore',
    tenthPercent: '96.2%',
    tenthYear: '2022',
    tenthBoard: 'CBSE',
    twelfthSchool: 'Bhavans Vidya Mandir, Coimbatore',
    twelfthPercent: '94.8%',
    twelfthCutoff: 192.5,
    cgpa: 9.12,
    sgpa: 9.30,
    attendance: 97,
    fatherName: 'Sridhar V',
    fatherOcc: 'Software Consultant',
    fatherMobile: '9840123450',
    fatherIncome: '6,50,000',
    motherName: 'Meenakshi S',
    motherOcc: 'Banking Professional',
    motherMobile: '9840123451',
    motherIncome: '4,50,000',
    guardianName: '',
    guardianRel: '',
    guardianMobile: '',
    emergencyContact: 'Sridhar V (Father)',
    emergencyMobile: '9840123450',
    familyIncome: '11,00,000',
    siblingsCount: 0,
    firstGraduate: 'No',
    feeTotal: 133500,
    feePaid: 133500,
    feeRemaining: 0,
    scholarshipType: 'Institutional Merit Scholarship',
    scholarshipAmount: '20,000',
    scholarshipId: 'IMS-SWCE-2026-004',
    feeRemarks: 'Full academic fee cleared.',
    accommodation: 'Day Scholar',
    hostelBlock: 'N/A',
    roomNo: 'N/A',
    messType: 'N/A',
    transportMode: 'College Bus',
    busRoute: 'Route 6 - Gandhipuram Express',
    busStop: 'Race Course Junction',
    vehicleNo: 'TN 38 BG 4421',
    bankName: 'HDFC Bank',
    accountHolder: 'Ananya Sridhar',
    accountNo: '50100293849182',
    ifsc: 'HDFC0000142',
    bankBranch: 'Race Course Road Branch',
    micr: '641240003',
    admissionNo: 'SWCE/ADM/2024/012',
    rollNo: '721124243012',
    regNo: '721124243012',
    quota: 'Government Quota (TNEA)',
    mentorName: 'Mrs. R. Malathi (Asst Prof CSE)',
    mentorEmail: 'malathi.cse@study-world.edu.in',
    verifiedByHOD: true,
    locked: true,
    verifiedDate: '10-09-2026 02:15 PM',
    hodRemarks: 'Documents verified and found authentic.',
    lastUpdated: Date.now() - 3600000,
    documents: {
      aadharFront: { fileName: 'Aadhar_Ananya_Front.pdf', size: '310 KB', uploadedAt: '08-09-2026', verified: true, status: 'Verified' },
      aadharBack: { fileName: 'Aadhar_Ananya_Back.pdf', size: '285 KB', uploadedAt: '08-09-2026', verified: true, status: 'Verified' },
      tenthMarksheet: { fileName: '10th_Ananya_CBSE.pdf', size: '470 KB', uploadedAt: '08-09-2026', verified: true, status: 'Verified' },
      twelfthMarksheet: { fileName: '12th_Ananya_CBSE.pdf', size: '510 KB', uploadedAt: '08-09-2026', verified: true, status: 'Verified' },
      tc: { fileName: 'TC_Ananya.pdf', size: '390 KB', uploadedAt: '08-09-2026', verified: true, status: 'Verified' },
      feesReceipt: { fileName: 'Fees_Receipt_Full_Year.pdf', size: '295 KB', uploadedAt: '08-09-2026', verified: true, status: 'Verified' },
      studentPhoto: { fileName: 'Photo_Ananya.jpg', size: '175 KB', uploadedAt: '08-09-2026', verified: true, status: 'Verified' },
      studentSignature: { fileName: 'Sign_Ananya.png', size: '88 KB', uploadedAt: '08-09-2026', verified: true, status: 'Verified' }
    }
  },

  'karthik.r@study-world.edu.in': {
    email: 'karthik.r@study-world.edu.in',
    studentId: 'SWCE-2024-CSE-045',
    firstName: 'Karthik',
    lastName: 'Raja',
    dob: '2004-11-23',
    gender: 'Male',
    bloodGroup: 'A+',
    aadhar: '839201948291',
    mobile: '9789012345',
    altMobile: '',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    community: 'MBC',
    religion: 'Hindu',
    motherTongue: 'Tamil',
    nationality: 'Indian',
    district: 'Tiruppur',
    state: 'Tamil Nadu',
    pincode: '641604',
    addressPerm: '12, Kumaran Street, Kangeyam Road, Tiruppur - 641604',
    addressCurr: 'SWCE Campus Hostel, Room 108-A, Kurinji Block',
    dept: 'CSE',
    year: 'III',
    semester: '5',
    batch: '2024-2028',
    admType: 'GQ',
    admDate: '2024-08-14',
    tenthSchool: 'Govt Boys Hr Sec School, Tiruppur',
    tenthPercent: '88.4%',
    tenthYear: '2022',
    tenthBoard: 'Tamil Nadu State Board',
    twelfthSchool: 'Govt Boys Hr Sec School, Tiruppur',
    twelfthPercent: '86.5%',
    twelfthCutoff: 178.0,
    cgpa: 8.15,
    sgpa: 8.20,
    attendance: 91,
    fatherName: 'Raja K',
    fatherOcc: 'Textile Factory Supervisor',
    fatherMobile: '9789012340',
    fatherIncome: '1,40,000',
    motherName: 'Selvi R',
    motherOcc: 'Garment Worker',
    motherMobile: '9789012341',
    motherIncome: '90,000',
    guardianName: '',
    guardianRel: '',
    guardianMobile: '',
    emergencyContact: 'Raja K (Father)',
    emergencyMobile: '9789012340',
    familyIncome: '2,30,000',
    siblingsCount: 2,
    firstGraduate: 'Yes',
    feeTotal: 133500,
    feePaid: 108500,
    feeRemaining: 25000,
    scholarshipType: 'First Graduate (FG) Concession',
    scholarshipAmount: '25,000',
    scholarshipId: 'FG-TN-2024-81920',
    feeRemarks: 'FG scholarship sanctioned. Balance pending.',
    accommodation: 'Hosteller',
    hostelBlock: 'Kurinji Boys Block A',
    roomNo: '108-A',
    messType: 'Non-Veg',
    transportMode: 'Hostel Walk',
    busRoute: 'N/A',
    busStop: 'Campus',
    vehicleNo: 'N/A',
    bankName: 'Canara Bank',
    accountHolder: 'Karthik Raja',
    accountNo: '1928101029384',
    ifsc: 'CNRB0001928',
    bankBranch: 'Tiruppur Main Branch',
    micr: '641015004',
    admissionNo: 'SWCE/ADM/2024/045',
    rollNo: '721124243045',
    regNo: '721124243045',
    quota: 'Government Quota (TNEA)',
    mentorName: 'Dr. P. Senthil Kumar (HOD CSE)',
    mentorEmail: 'hod.cse@study-world.edu.in',
    verifiedByHOD: false,
    locked: false,
    verifiedDate: 'Pending Review',
    hodRemarks: 'FG certificate under verification with Revenue Dept.',
    lastUpdated: Date.now() - 5000000,
    documents: {
      aadharFront: { fileName: 'Aadhar_Karthik.pdf', size: '305 KB', uploadedAt: '10-09-2026', verified: true, status: 'Verified' },
      firstGraduate: { fileName: 'FG_Certificate.pdf', size: '420 KB', uploadedAt: '10-09-2026', verified: false, status: 'Pending' },
      income: { fileName: 'Income_Tahsildar.pdf', size: '380 KB', uploadedAt: '10-09-2026', verified: true, status: 'Verified' }
    }
  },

  'priya.k@study-world.edu.in': {
    email: 'priya.k@study-world.edu.in',
    studentId: 'SWCE-2023-ECE-029',
    firstName: 'Priya',
    lastName: 'Kumaran',
    dob: '2003-09-08',
    gender: 'Female',
    bloodGroup: 'AB+',
    aadhar: '384910294819',
    mobile: '9842109876',
    altMobile: '',
    photo: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&auto=format&fit=crop&q=80',
    community: 'SC',
    religion: 'Hindu',
    motherTongue: 'Tamil',
    nationality: 'Indian',
    district: 'Pollachi',
    state: 'Tamil Nadu',
    pincode: '642001',
    addressPerm: '5/12, New Gandhi Street, Mahalingapuram, Pollachi - 642001',
    addressCurr: 'SWCE Kurinji Girls Hostel, Room 302',
    dept: 'ECE',
    year: 'IV',
    semester: '8',
    batch: '2023-2027',
    admType: 'GQ',
    admDate: '2023-08-20',
    tenthSchool: 'Municipal Girls Hr Sec School, Pollachi',
    tenthPercent: '94.5%',
    tenthYear: '2021',
    tenthBoard: 'State Board',
    twelfthSchool: 'Municipal Girls Hr Sec School, Pollachi',
    twelfthPercent: '92.0%',
    twelfthCutoff: 188.0,
    cgpa: 8.92,
    sgpa: 9.10,
    attendance: 96,
    fatherName: 'Kumaran M',
    fatherOcc: 'Govt Employee',
    fatherMobile: '9842109870',
    fatherIncome: '2,20,000',
    motherName: 'Kavitha K',
    motherOcc: 'Teacher',
    motherMobile: '9842109871',
    motherIncome: '1,80,000',
    guardianName: '',
    guardianRel: '',
    guardianMobile: '',
    emergencyContact: 'Kumaran M (Father)',
    emergencyMobile: '9842109870',
    familyIncome: '4,00,000',
    siblingsCount: 1,
    firstGraduate: 'No',
    feeTotal: 125000,
    feePaid: 125000,
    feeRemaining: 0,
    scholarshipType: 'Post Matric Scholarship',
    scholarshipAmount: '35,000',
    scholarshipId: 'PMS-TN-2026-3391',
    feeRemarks: 'Fees settled via scholarship & self.',
    accommodation: 'Hosteller',
    hostelBlock: 'Girls Hostel B',
    roomNo: '302',
    messType: 'Veg',
    transportMode: 'Hostel Walk',
    busRoute: 'N/A',
    busStop: 'Campus',
    vehicleNo: 'N/A',
    bankName: 'Indian Overseas Bank (IOB)',
    accountHolder: 'Priya Kumaran',
    accountNo: '028101000049182',
    ifsc: 'IOBA0000281',
    bankBranch: 'Pollachi Main Branch',
    micr: '642020002',
    admissionNo: 'SWCE/ADM/2023/029',
    rollNo: '721123244029',
    regNo: '721123244029',
    quota: 'Government Quota (TNEA)',
    mentorName: 'Dr. S. Prakash (HOD ECE)',
    mentorEmail: 'hod.ece@study-world.edu.in',
    verifiedByHOD: true,
    locked: true,
    verifiedDate: '02-09-2026 04:00 PM',
    hodRemarks: 'Verified all 8 categories.',
    lastUpdated: Date.now() - 15000000,
    documents: {
      aadharFront: { fileName: 'Aadhar_Priya.pdf', size: '310 KB', uploadedAt: '01-09-2026', verified: true, status: 'Verified' },
      tenthMarksheet: { fileName: '10th_Priya.pdf', size: '490 KB', uploadedAt: '01-09-2026', verified: true, status: 'Verified' },
      twelfthMarksheet: { fileName: '12th_Priya.pdf', size: '510 KB', uploadedAt: '01-09-2026', verified: true, status: 'Verified' }
    }
  },

  'kaviya.v@study-world.edu.in': {
    email: 'kaviya.v@study-world.edu.in',
    studentId: 'SWCE-2024-ECE-018',
    firstName: 'Kaviya',
    lastName: 'Venkatesh',
    dob: '2005-04-12',
    gender: 'Female',
    bloodGroup: 'B+',
    aadhar: '583920194821',
    mobile: '9786123456',
    altMobile: '9786123450',
    photo: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&auto=format&fit=crop&q=80',
    community: 'BC',
    religion: 'Hindu',
    motherTongue: 'Tamil',
    nationality: 'Indian',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    pincode: '641012',
    addressPerm: '24, Cross Cut Road, Gandhipuram, Coimbatore - 641012',
    addressCurr: '24, Cross Cut Road, Gandhipuram, Coimbatore - 641012',
    dept: 'ECE',
    year: 'II',
    semester: '3',
    batch: '2024-2028',
    admType: 'GQ',
    admDate: '2024-08-16',
    tenthSchool: 'Avila Convent, Coimbatore',
    tenthPercent: '91.8%',
    tenthYear: '2022',
    tenthBoard: 'Matriculation',
    twelfthSchool: 'Avila Convent, Coimbatore',
    twelfthPercent: '88.4%',
    twelfthCutoff: 182.0,
    cgpa: 8.40,
    sgpa: 8.50,
    attendance: 93,
    fatherName: 'Venkatesh S',
    fatherOcc: 'Retail Merchant',
    fatherMobile: '9786123450',
    fatherIncome: '3,00,000',
    motherName: 'Radha V',
    motherOcc: 'Homemaker',
    motherMobile: '9786123451',
    motherIncome: '0',
    guardianName: '',
    guardianRel: '',
    guardianMobile: '',
    emergencyContact: 'Venkatesh S (Father)',
    emergencyMobile: '9786123450',
    familyIncome: '3,00,000',
    siblingsCount: 1,
    firstGraduate: 'No',
    feeTotal: 125000,
    feePaid: 70000,
    feeRemaining: 55000,
    scholarshipType: 'None',
    scholarshipAmount: '0',
    scholarshipId: '',
    feeRemarks: 'Term 2 fees pending.',
    accommodation: 'Day Scholar',
    hostelBlock: 'N/A',
    roomNo: 'N/A',
    messType: 'N/A',
    transportMode: 'College Bus',
    busRoute: 'Route 4B - Gandhipuram',
    busStop: 'Cross Cut Signal',
    vehicleNo: 'TN 38 AH 9981',
    bankName: 'Indian Bank',
    accountHolder: 'Kaviya Venkatesh',
    accountNo: '62910293847',
    ifsc: 'IDIB000G012',
    bankBranch: 'Gandhipuram Branch',
    micr: '641019005',
    admissionNo: 'SWCE/ADM/2024/018',
    rollNo: '721124244018',
    regNo: '721124244018',
    quota: 'Government Quota (TNEA)',
    mentorName: 'Dr. S. Prakash (HOD ECE)',
    mentorEmail: 'hod.ece@study-world.edu.in',
    verifiedByHOD: true,
    locked: true,
    verifiedDate: '14-09-2026 10:00 AM',
    hodRemarks: 'Documents and fees structure verified.',
    lastUpdated: Date.now() - 4200000,
    documents: {
      aadharFront: { fileName: 'Aadhar_Kaviya.pdf', size: '315 KB', uploadedAt: '11-09-2026', verified: true, status: 'Verified' },
      tenthMarksheet: { fileName: '10th_Kaviya.pdf', size: '475 KB', uploadedAt: '11-09-2026', verified: true, status: 'Verified' },
      twelfthMarksheet: { fileName: '12th_Kaviya.pdf', size: '515 KB', uploadedAt: '11-09-2026', verified: true, status: 'Verified' }
    }
  },

  'suresh.k@study-world.edu.in': {
    email: 'suresh.k@study-world.edu.in',
    studentId: 'SWCE-2023-MECH-034',
    firstName: 'Suresh',
    lastName: 'Kumar',
    dob: '2004-03-25',
    gender: 'Male',
    bloodGroup: 'O+',
    aadhar: '928374619283',
    mobile: '9843210987',
    altMobile: '9843210980',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    community: 'BC',
    religion: 'Hindu',
    motherTongue: 'Tamil',
    nationality: 'Indian',
    district: 'Salem',
    state: 'Tamil Nadu',
    pincode: '636007',
    addressPerm: '88, Steel Plant Road, Salem - 636007',
    addressCurr: 'SWCE Marutham Boys Hostel, Room 112',
    dept: 'MECH',
    year: 'III',
    semester: '6',
    batch: '2023-2027',
    admType: 'GQ',
    admDate: '2023-08-18',
    tenthSchool: 'Govt Model Hr Sec School, Salem',
    tenthPercent: '87.2%',
    tenthYear: '2021',
    tenthBoard: 'State Board',
    twelfthSchool: 'Govt Model Hr Sec School, Salem',
    twelfthPercent: '84.6%',
    twelfthCutoff: 174.5,
    cgpa: 7.95,
    sgpa: 8.10,
    attendance: 90,
    fatherName: 'Krishnan P',
    fatherOcc: 'Steel Plant Technician',
    fatherMobile: '9843210980',
    fatherIncome: '2,40,000',
    motherName: 'Mallika K',
    motherOcc: 'Homemaker',
    motherMobile: '9843210981',
    motherIncome: '0',
    guardianName: '',
    guardianRel: '',
    guardianMobile: '',
    emergencyContact: 'Krishnan P (Father)',
    emergencyMobile: '9843210980',
    familyIncome: '2,40,000',
    siblingsCount: 1,
    firstGraduate: 'No',
    feeTotal: 135000,
    feePaid: 120000,
    feeRemaining: 15000,
    scholarshipType: 'BC Welfare Scholarship',
    scholarshipAmount: '12,500',
    scholarshipId: 'BCW-TN-2025-4491',
    feeRemarks: 'Hostel mess fee installment remaining ₹15,000.',
    accommodation: 'Hosteller',
    hostelBlock: 'Marutham Boys Block B',
    roomNo: '112',
    messType: 'Non-Veg',
    transportMode: 'Hostel Walk',
    busRoute: 'N/A',
    busStop: 'Campus',
    vehicleNo: 'N/A',
    bankName: 'State Bank of India',
    accountHolder: 'Suresh Kumar',
    accountNo: '30928194829',
    ifsc: 'SBIN0000912',
    bankBranch: 'Salem Town Branch',
    micr: '636002008',
    admissionNo: 'SWCE/ADM/2023/034',
    rollNo: '721123245034',
    regNo: '721123245034',
    quota: 'Government Quota (TNEA)',
    mentorName: 'Dr. M. Muruganandam (HOD MECH)',
    mentorEmail: 'hod.mech@study-world.edu.in',
    verifiedByHOD: true,
    locked: true,
    verifiedDate: '12-09-2026 03:30 PM',
    hodRemarks: 'Verified mechanical workshop credentials and records.',
    lastUpdated: Date.now() - 6000000,
    documents: {
      aadharFront: { fileName: 'Aadhar_Suresh.pdf', size: '325 KB', uploadedAt: '09-09-2026', verified: true, status: 'Verified' },
      tenthMarksheet: { fileName: '10th_Suresh.pdf', size: '480 KB', uploadedAt: '09-09-2026', verified: true, status: 'Verified' },
      twelfthMarksheet: { fileName: '12th_Suresh.pdf', size: '520 KB', uploadedAt: '09-09-2026', verified: true, status: 'Verified' }
    }
  },

  'vignesh.k@study-world.edu.in': {
    email: 'vignesh.k@study-world.edu.in',
    studentId: 'SWCE-2024-MECH-051',
    firstName: 'Vigneshwaran',
    lastName: 'K',
    dob: '2005-07-19',
    gender: 'Male',
    bloodGroup: 'A1B+',
    aadhar: '839201948273',
    mobile: '9894123456',
    altMobile: '9894123450',
    photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&auto=format&fit=crop&q=80',
    community: 'MBC',
    religion: 'Hindu',
    motherTongue: 'Tamil',
    nationality: 'Indian',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    pincode: '641008',
    addressPerm: '10, Thondamuthur Road, Vadavalli, Coimbatore - 641008',
    addressCurr: '10, Thondamuthur Road, Vadavalli, Coimbatore - 641008',
    dept: 'MECH',
    year: 'II',
    semester: '4',
    batch: '2024-2028',
    admType: 'GQ',
    admDate: '2024-08-22',
    tenthSchool: 'Chinmaya Vidyalaya, Vadavalli',
    tenthPercent: '89.0%',
    tenthYear: '2022',
    tenthBoard: 'CBSE',
    twelfthSchool: 'Chinmaya Vidyalaya, Vadavalli',
    twelfthPercent: '86.0%',
    twelfthCutoff: 177.0,
    cgpa: 8.22,
    sgpa: 8.35,
    attendance: 92,
    fatherName: 'Kandasamy M',
    fatherOcc: 'Workshop Owner',
    fatherMobile: '9894123450',
    fatherIncome: '3,20,000',
    motherName: 'Geetha K',
    motherOcc: 'Homemaker',
    motherMobile: '9894123451',
    motherIncome: '0',
    guardianName: '',
    guardianRel: '',
    guardianMobile: '',
    emergencyContact: 'Kandasamy M (Father)',
    emergencyMobile: '9894123450',
    familyIncome: '3,20,000',
    siblingsCount: 1,
    firstGraduate: 'No',
    feeTotal: 135000,
    feePaid: 135000,
    feeRemaining: 0,
    scholarshipType: 'None',
    scholarshipAmount: '0',
    scholarshipId: '',
    feeRemarks: 'Full fee paid.',
    accommodation: 'Day Scholar',
    hostelBlock: 'N/A',
    roomNo: 'N/A',
    messType: 'N/A',
    transportMode: 'Two Wheeler',
    busRoute: 'N/A',
    busStop: 'Vadavalli',
    vehicleNo: 'TN 38 DD 7112',
    bankName: 'Karur Vysya Bank',
    accountHolder: 'Vigneshwaran K',
    accountNo: '1628101029384',
    ifsc: 'KVBL0001628',
    bankBranch: 'Vadavalli Branch',
    micr: '641053008',
    admissionNo: 'SWCE/ADM/2024/051',
    rollNo: '721124245051',
    regNo: '721124245051',
    quota: 'Government Quota (TNEA)',
    mentorName: 'Dr. M. Muruganandam (HOD MECH)',
    mentorEmail: 'hod.mech@study-world.edu.in',
    verifiedByHOD: true,
    locked: true,
    verifiedDate: '16-09-2026 11:45 AM',
    hodRemarks: 'Verified.',
    lastUpdated: Date.now() - 7200000,
    documents: {
      aadharFront: { fileName: 'Aadhar_Vignesh.pdf', size: '330 KB', uploadedAt: '10-09-2026', verified: true, status: 'Verified' },
      tenthMarksheet: { fileName: '10th_Vignesh.pdf', size: '490 KB', uploadedAt: '10-09-2026', verified: true, status: 'Verified' },
      twelfthMarksheet: { fileName: '12th_Vignesh.pdf', size: '530 KB', uploadedAt: '10-09-2026', verified: true, status: 'Verified' }
    }
  },

  'sneha.r@study-world.edu.in': {
    email: 'sneha.r@study-world.edu.in',
    studentId: 'SWCE-2024-AIDS-019',
    firstName: 'Sneha',
    lastName: 'Ramakrishnan',
    dob: '2005-08-30',
    gender: 'Female',
    bloodGroup: 'O-',
    aadhar: '629102938471',
    mobile: '9790123456',
    altMobile: '9790123450',
    photo: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200&auto=format&fit=crop&q=80',
    community: 'BC',
    religion: 'Hindu',
    motherTongue: 'Tamil',
    nationality: 'Indian',
    district: 'Pollachi',
    state: 'Tamil Nadu',
    pincode: '642002',
    addressPerm: '14, Palakkad Main Road, Pollachi - 642002',
    addressCurr: '14, Palakkad Main Road, Pollachi - 642002',
    dept: 'AIDS',
    year: 'II',
    semester: '4',
    batch: '2024-2028',
    admType: 'GQ',
    admDate: '2024-08-11',
    tenthSchool: 'Sri Lathangi Vidya Mandir, Pollachi',
    tenthPercent: '97.4%',
    tenthYear: '2022',
    tenthBoard: 'Matriculation',
    twelfthSchool: 'Sri Lathangi Vidya Mandir, Pollachi',
    twelfthPercent: '96.2%',
    twelfthCutoff: 195.0,
    cgpa: 9.35,
    sgpa: 9.50,
    attendance: 98,
    fatherName: 'Ramakrishnan T',
    fatherOcc: 'Accountant',
    fatherMobile: '9790123450',
    fatherIncome: '2,80,000',
    motherName: 'Devi R',
    motherOcc: 'Homemaker',
    motherMobile: '9790123451',
    motherIncome: '0',
    guardianName: '',
    guardianRel: '',
    guardianMobile: '',
    emergencyContact: 'Ramakrishnan T (Father)',
    emergencyMobile: '9790123450',
    familyIncome: '2,80,000',
    siblingsCount: 1,
    firstGraduate: 'Yes',
    feeTotal: 133500,
    feePaid: 133500,
    feeRemaining: 0,
    scholarshipType: 'First Graduate + DOTE AI Merit',
    scholarshipAmount: '35,000',
    scholarshipId: 'FG-TN-2024-99128',
    feeRemarks: 'Full fees cleared via scholarship & demand draft.',
    accommodation: 'Day Scholar',
    hostelBlock: 'N/A',
    roomNo: 'N/A',
    messType: 'N/A',
    transportMode: 'College Bus',
    busRoute: 'Route 12 - Pollachi Direct',
    busStop: 'Pollachi Old Bus Stand',
    vehicleNo: 'TN 38 CN 1928',
    bankName: 'City Union Bank (CUB)',
    accountHolder: 'Sneha Ramakrishnan',
    accountNo: '510909010029384',
    ifsc: 'CIUB0000510',
    bankBranch: 'Pollachi Branch',
    micr: '642054002',
    admissionNo: 'SWCE/ADM/2024/019',
    rollNo: '721124248019',
    regNo: '721124248019',
    quota: 'Government Quota (TNEA)',
    mentorName: 'Dr. K. Ramesh (HOD AI&DS)',
    mentorEmail: 'hod.aids@study-world.edu.in',
    verifiedByHOD: true,
    locked: true,
    verifiedDate: '11-09-2026 09:30 AM',
    hodRemarks: 'Exemplary academic record. First Graduate verified.',
    lastUpdated: Date.now() - 3200000,
    documents: {
      aadharFront: { fileName: 'Aadhar_Sneha.pdf', size: '310 KB', uploadedAt: '07-09-2026', verified: true, status: 'Verified' },
      firstGraduate: { fileName: 'FG_Sneha_Tahsildar.pdf', size: '440 KB', uploadedAt: '07-09-2026', verified: true, status: 'Verified' },
      tenthMarksheet: { fileName: '10th_Sneha.pdf', size: '460 KB', uploadedAt: '07-09-2026', verified: true, status: 'Verified' },
      twelfthMarksheet: { fileName: '12th_Sneha.pdf', size: '505 KB', uploadedAt: '07-09-2026', verified: true, status: 'Verified' }
    }
  },

  'mohamed.arif@study-world.edu.in': {
    email: 'mohamed.arif@study-world.edu.in',
    studentId: 'SWCE-2024-AIDS-042',
    firstName: 'Mohamed',
    lastName: 'Arif',
    dob: '2004-12-05',
    gender: 'Male',
    bloodGroup: 'B+',
    aadhar: '739281948291',
    mobile: '9840912345',
    altMobile: '9840912340',
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    community: 'BCM',
    religion: 'Muslim',
    motherTongue: 'Tamil',
    nationality: 'Indian',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    pincode: '641001',
    addressPerm: '29, Ukkadam Big Bazaar, Coimbatore - 641001',
    addressCurr: 'SWCE Campus Hostel, Room 305-A, Kurinji Block',
    dept: 'AIDS',
    year: 'III',
    semester: '5',
    batch: '2024-2028',
    admType: 'GQ',
    admDate: '2024-08-15',
    tenthSchool: 'Al-Ameen Hr Sec School, Coimbatore',
    tenthPercent: '90.5%',
    tenthYear: '2022',
    tenthBoard: 'State Board',
    twelfthSchool: 'Al-Ameen Hr Sec School, Coimbatore',
    twelfthPercent: '89.2%',
    twelfthCutoff: 184.5,
    cgpa: 8.65,
    sgpa: 8.80,
    attendance: 95,
    fatherName: 'Abdul Rahman M',
    fatherOcc: 'Automobile Spare Parts Merchant',
    fatherMobile: '9840912340',
    fatherIncome: '2,60,000',
    motherName: 'Fathima A',
    motherOcc: 'Homemaker',
    motherMobile: '9840912341',
    motherIncome: '0',
    guardianName: '',
    guardianRel: '',
    guardianMobile: '',
    emergencyContact: 'Abdul Rahman M (Father)',
    emergencyMobile: '9840912340',
    familyIncome: '2,60,000',
    siblingsCount: 2,
    firstGraduate: 'No',
    feeTotal: 133500,
    feePaid: 103500,
    feeRemaining: 30000,
    scholarshipType: 'Minority Welfare Scholarship (MOMA)',
    scholarshipAmount: '20,000',
    scholarshipId: 'MOMA-TN-2025-0192',
    feeRemarks: 'MOMA portal verification approved.',
    accommodation: 'Hosteller',
    hostelBlock: 'Kurinji Boys Block A',
    roomNo: '305-A',
    messType: 'Non-Veg',
    transportMode: 'Hostel Walk',
    busRoute: 'N/A',
    busStop: 'Campus',
    vehicleNo: 'N/A',
    bankName: 'Axis Bank',
    accountHolder: 'Mohamed Arif',
    accountNo: '92101002938475',
    ifsc: 'UTIB0000342',
    bankBranch: 'Ukkadam Branch',
    micr: '641211003',
    admissionNo: 'SWCE/ADM/2024/042',
    rollNo: '721124248042',
    regNo: '721124248042',
    quota: 'Government Quota (TNEA)',
    mentorName: 'Dr. K. Ramesh (HOD AI&DS)',
    mentorEmail: 'hod.aids@study-world.edu.in',
    verifiedByHOD: true,
    locked: true,
    verifiedDate: '15-09-2026 03:00 PM',
    hodRemarks: 'Minority welfare documents verified.',
    lastUpdated: Date.now() - 4800000,
    documents: {
      aadharFront: { fileName: 'Aadhar_Arif.pdf', size: '315 KB', uploadedAt: '12-09-2026', verified: true, status: 'Verified' },
      community: { fileName: 'Community_BCM.pdf', size: '360 KB', uploadedAt: '12-09-2026', verified: true, status: 'Verified' },
      tenthMarksheet: { fileName: '10th_Arif.pdf', size: '480 KB', uploadedAt: '12-09-2026', verified: true, status: 'Verified' }
    }
  },

  'dinesh.m@study-world.edu.in': {
    email: 'dinesh.m@study-world.edu.in',
    studentId: 'SWCE-2023-CIVIL-015',
    firstName: 'Dinesh',
    lastName: 'Murugan',
    dob: '2003-10-14',
    gender: 'Male',
    bloodGroup: 'B+',
    aadhar: '839281948291',
    mobile: '9842912345',
    altMobile: '9842912340',
    photo: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
    community: 'MBC',
    religion: 'Hindu',
    motherTongue: 'Tamil',
    nationality: 'Indian',
    district: 'Erode',
    state: 'Tamil Nadu',
    pincode: '638001',
    addressPerm: '45, Perundurai Road, Erode - 638001',
    addressCurr: 'SWCE Marutham Boys Hostel, Room 210',
    dept: 'CIVIL',
    year: 'IV',
    semester: '7',
    batch: '2023-2027',
    admType: 'GQ',
    admDate: '2023-08-25',
    tenthSchool: 'Govt Model Hr Sec School, Erode',
    tenthPercent: '88.0%',
    tenthYear: '2021',
    tenthBoard: 'State Board',
    twelfthSchool: 'Govt Model Hr Sec School, Erode',
    twelfthPercent: '85.4%',
    twelfthCutoff: 176.0,
    cgpa: 8.10,
    sgpa: 8.25,
    attendance: 91,
    fatherName: 'Murugan S',
    fatherOcc: 'Civil Contractor',
    fatherMobile: '9842912340',
    fatherIncome: '2,50,000',
    motherName: 'Parvathi M',
    motherOcc: 'Homemaker',
    motherMobile: '9842912341',
    motherIncome: '0',
    guardianName: '',
    guardianRel: '',
    guardianMobile: '',
    emergencyContact: 'Murugan S (Father)',
    emergencyMobile: '9842912340',
    familyIncome: '2,50,000',
    siblingsCount: 1,
    firstGraduate: 'No',
    feeTotal: 125000,
    feePaid: 125000,
    feeRemaining: 0,
    scholarshipType: 'None',
    scholarshipAmount: '0',
    scholarshipId: '',
    feeRemarks: 'Tuition and laboratory fee cleared.',
    accommodation: 'Hosteller',
    hostelBlock: 'Marutham Boys Block B',
    roomNo: '210',
    messType: 'Non-Veg',
    transportMode: 'Hostel Walk',
    busRoute: 'N/A',
    busStop: 'Campus',
    vehicleNo: 'N/A',
    bankName: 'Canara Bank',
    accountHolder: 'Dinesh Murugan',
    accountNo: '2819101029384',
    ifsc: 'CNRB0002819',
    bankBranch: 'Erode Main Branch',
    micr: '638015002',
    admissionNo: 'SWCE/ADM/2023/015',
    rollNo: '721123242015',
    regNo: '721123242015',
    quota: 'Government Quota (TNEA)',
    mentorName: 'Dr. C. Natarajan (HOD CIVIL)',
    mentorEmail: 'hod.civil@study-world.edu.in',
    verifiedByHOD: true,
    locked: true,
    verifiedDate: '10-09-2026 05:00 PM',
    hodRemarks: 'Verified surveying and internship records.',
    lastUpdated: Date.now() - 8400000,
    documents: {
      aadharFront: { fileName: 'Aadhar_Dinesh.pdf', size: '320 KB', uploadedAt: '08-09-2026', verified: true, status: 'Verified' },
      tenthMarksheet: { fileName: '10th_Dinesh.pdf', size: '475 KB', uploadedAt: '08-09-2026', verified: true, status: 'Verified' }
    }
  },

  'arvind.s@study-world.edu.in': {
    email: 'arvind.s@study-world.edu.in',
    studentId: 'SWCE-2024-EEE-022',
    firstName: 'Arvind',
    lastName: 'Swaminathan',
    dob: '2004-10-18',
    gender: 'Male',
    bloodGroup: 'O+',
    aadhar: '938201948291',
    mobile: '9843912345',
    altMobile: '9843912340',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    community: 'OC',
    religion: 'Hindu',
    motherTongue: 'Tamil',
    nationality: 'Indian',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    pincode: '641004',
    addressPerm: '12, Bharathi Park 7th Cross, Saibaba Colony, Coimbatore - 641004',
    addressCurr: '12, Bharathi Park 7th Cross, Saibaba Colony, Coimbatore - 641004',
    dept: 'EEE',
    year: 'III',
    semester: '6',
    batch: '2024-2028',
    admType: 'GQ',
    admDate: '2024-08-17',
    tenthSchool: 'Lisieux Matric Hr Sec School, Saibaba Colony',
    tenthPercent: '92.4%',
    tenthYear: '2022',
    tenthBoard: 'Matriculation',
    twelfthSchool: 'Lisieux Matric Hr Sec School, Saibaba Colony',
    twelfthPercent: '90.0%',
    twelfthCutoff: 185.0,
    cgpa: 8.52,
    sgpa: 8.70,
    attendance: 94,
    fatherName: 'Swaminathan K',
    fatherOcc: 'Electrical Engineer (TANGEDCO)',
    fatherMobile: '9843912340',
    fatherIncome: '5,00,000',
    motherName: 'Uma S',
    motherOcc: 'School Teacher',
    motherMobile: '9843912341',
    motherIncome: '3,00,000',
    guardianName: '',
    guardianRel: '',
    guardianMobile: '',
    emergencyContact: 'Swaminathan K (Father)',
    emergencyMobile: '9843912340',
    familyIncome: '8,00,000',
    siblingsCount: 1,
    firstGraduate: 'No',
    feeTotal: 133500,
    feePaid: 113500,
    feeRemaining: 20000,
    scholarshipType: 'None',
    scholarshipAmount: '0',
    scholarshipId: '',
    feeRemarks: 'Term 2 examination fee balance ₹20,000.',
    accommodation: 'Day Scholar',
    hostelBlock: 'N/A',
    roomNo: 'N/A',
    messType: 'N/A',
    transportMode: 'College Bus',
    busRoute: 'Route 3 - Saibaba Colony & Thudiyalur',
    busStop: 'Saibaba Colony NSR Road',
    vehicleNo: 'TN 38 BE 5541',
    bankName: 'State Bank of India',
    accountHolder: 'Arvind Swaminathan',
    accountNo: '39281019283',
    ifsc: 'SBIN0007238',
    bankBranch: 'Saibaba Colony Branch',
    micr: '641002028',
    admissionNo: 'SWCE/ADM/2024/022',
    rollNo: '721124246022',
    regNo: '721124246022',
    quota: 'Government Quota (TNEA)',
    mentorName: 'Dr. V. Karthikeyan (HOD EEE)',
    mentorEmail: 'hod.eee@study-world.edu.in',
    verifiedByHOD: true,
    locked: true,
    verifiedDate: '14-09-2026 02:00 PM',
    hodRemarks: 'Circuits laboratory clearance verified.',
    lastUpdated: Date.now() - 5600000,
    documents: {
      aadharFront: { fileName: 'Aadhar_Arvind.pdf', size: '310 KB', uploadedAt: '10-09-2026', verified: true, status: 'Verified' },
      tenthMarksheet: { fileName: '10th_Arvind.pdf', size: '480 KB', uploadedAt: '10-09-2026', verified: true, status: 'Verified' },
      twelfthMarksheet: { fileName: '12th_Arvind.pdf', size: '520 KB', uploadedAt: '10-09-2026', verified: true, status: 'Verified' }
    }
  },

  'divya.r@study-world.edu.in': {
    email: 'divya.r@study-world.edu.in',
    studentId: 'SWCE-2024-IT-014',
    firstName: 'Divya',
    lastName: 'Ramesh',
    dob: '2005-01-20',
    gender: 'Female',
    bloodGroup: 'A+',
    aadhar: '482910394829',
    mobile: '9840212345',
    altMobile: '9840212340',
    photo: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&auto=format&fit=crop&q=80',
    community: 'BC',
    religion: 'Hindu',
    motherTongue: 'Tamil',
    nationality: 'Indian',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    pincode: '641006',
    addressPerm: '82, Sathy Main Road, Ganapathy, Coimbatore - 641006',
    addressCurr: '82, Sathy Main Road, Ganapathy, Coimbatore - 641006',
    dept: 'IT',
    year: 'II',
    semester: '3',
    batch: '2024-2028',
    admType: 'GQ',
    admDate: '2024-08-13',
    tenthSchool: 'CMS Matric Hr Sec School, Ganapathy',
    tenthPercent: '95.0%',
    tenthYear: '2022',
    tenthBoard: 'Matriculation',
    twelfthSchool: 'CMS Matric Hr Sec School, Ganapathy',
    twelfthPercent: '93.2%',
    twelfthCutoff: 190.0,
    cgpa: 8.88,
    sgpa: 9.05,
    attendance: 96,
    fatherName: 'Ramesh B',
    fatherOcc: 'Textile Machinery Spares',
    fatherMobile: '9840212340',
    fatherIncome: '3,80,000',
    motherName: 'Shanthi R',
    motherOcc: 'Homemaker',
    motherMobile: '9840212341',
    motherIncome: '0',
    guardianName: '',
    guardianRel: '',
    guardianMobile: '',
    emergencyContact: 'Ramesh B (Father)',
    emergencyMobile: '9840212340',
    familyIncome: '3,80,000',
    siblingsCount: 1,
    firstGraduate: 'No',
    feeTotal: 133500,
    feePaid: 133500,
    feeRemaining: 0,
    scholarshipType: 'None',
    scholarshipAmount: '0',
    scholarshipId: '',
    feeRemarks: 'Cleared full year.',
    accommodation: 'Day Scholar',
    hostelBlock: 'N/A',
    roomNo: 'N/A',
    messType: 'N/A',
    transportMode: 'College Bus',
    busRoute: 'Route 8 - Ganapathy & Sathy Road',
    busStop: 'Ganapathy Bus Stand',
    vehicleNo: 'TN 38 BK 2918',
    bankName: 'Punjab National Bank',
    accountHolder: 'Divya Ramesh',
    accountNo: '1829100293847',
    ifsc: 'PUNB0018291',
    bankBranch: 'Ganapathy Branch',
    micr: '641024003',
    admissionNo: 'SWCE/ADM/2024/014',
    rollNo: '721124247014',
    regNo: '721124247014',
    quota: 'Government Quota (TNEA)',
    mentorName: 'Dr. G. Anand (HOD IT)',
    mentorEmail: 'hod.it@study-world.edu.in',
    verifiedByHOD: true,
    locked: true,
    verifiedDate: '13-09-2026 04:30 PM',
    hodRemarks: 'Full profile and documents verified.',
    lastUpdated: Date.now() - 6400000,
    documents: {
      aadharFront: { fileName: 'Aadhar_Divya.pdf', size: '320 KB', uploadedAt: '09-09-2026', verified: true, status: 'Verified' },
      tenthMarksheet: { fileName: '10th_Divya.pdf', size: '480 KB', uploadedAt: '09-09-2026', verified: true, status: 'Verified' },
      twelfthMarksheet: { fileName: '12th_Divya.pdf', size: '510 KB', uploadedAt: '09-09-2026', verified: true, status: 'Verified' }
    }
  }
};

// Aliases for Sakthi Madhavan so that any student login finds Sakthi's full master profile
const sakthiAliases = [
  'student_001@study-world.edu.in',
  'madhavan2006sakthi@gmail.com',
  'sakthi@study-world.edu.in',
  'student_001'
];
sakthiAliases.forEach(alias => {
  if (!INITIAL_MASTER_STUDENTS[alias]) {
    INITIAL_MASTER_STUDENTS[alias] = {
      ...INITIAL_MASTER_STUDENTS['student@study-world.edu.in'],
      email: alias
    };
  }
});

// In-memory persistent master data store
let masterDataStore = { ...INITIAL_MASTER_STUDENTS };

function getDefaultMasterData() {
  return JSON.parse(JSON.stringify(INITIAL_MASTER_STUDENTS));
}

function getMasterDataStore() {
  return masterDataStore;
}

function getStudentMasterRecord(identifier) {
  if (!identifier) return masterDataStore['student@study-world.edu.in'];
  const idLower = String(identifier).toLowerCase().trim();
  
  // 1. Direct email lookup
  if (masterDataStore[idLower]) {
    return masterDataStore[idLower];
  }
  
  // 2. Check Sakthi aliases
  if (idLower.includes('sakthi') || idLower.includes('madhavan') || idLower.includes('student_001') || idLower === 'student') {
    const sakthi = masterDataStore['student@study-world.edu.in'];
    return { ...sakthi, email: identifier };
  }

  // 3. Search by Roll No, Reg No, or Name
  for (const email in masterDataStore) {
    const s = masterDataStore[email];
    if (s.rollNo === identifier || s.regNo === identifier || s.studentId === identifier) {
      return s;
    }
    const fullName = (s.firstName + ' ' + s.lastName).toLowerCase();
    if (fullName.includes(idLower)) {
      return s;
    }
  }

  // Fallback to Sakthi template with requested identifier
  const fallback = JSON.parse(JSON.stringify(masterDataStore['student@study-world.edu.in']));
  fallback.email = identifier;
  masterDataStore[idLower] = fallback;
  return fallback;
}

function saveStudentMasterRecord(profile) {
  if (!profile || !profile.email) {
    throw new Error('Valid student profile and email required');
  }
  const email = profile.email.toLowerCase().trim();
  masterDataStore[email] = {
    ...(masterDataStore[email] || {}),
    ...profile,
    lastUpdated: Date.now()
  };
  return masterDataStore[email];
}

function getAllMasterStudentsList() {
  // Return unique students by rollNo to avoid duplicate alias entries
  const seenRolls = new Set();
  const list = [];
  
  for (const email in masterDataStore) {
    const s = masterDataStore[email];
    const roll = s.rollNo || s.regNo || email;
    if (!seenRolls.has(roll)) {
      seenRolls.add(roll);
      list.push(s);
    }
  }
  return list;
}

function getStaffProfilesMap() {
  const map = {};
  const all = getAllMasterStudentsList();
  all.forEach(s => {
    map[s.email] = {
      studentName: s.firstName + ' ' + s.lastName,
      regNo: s.regNo || s.rollNo,
      rollNo: s.rollNo,
      dept: s.dept,
      year: s.year,
      semester: String(s.semester || '6'),
      attendancePercent: s.attendance || 90,
      leavePercent: Math.max(0, 100 - (s.attendance || 90)),
      parentNumber: s.fatherMobile || s.motherMobile || '9876543210',
      guardianNumber: s.guardianMobile || '',
      studentNumber: s.mobile || '9123456780',
      userMailId: s.email,
      subscription: 'Yours obediently',
      studentSignature: s.firstName + ' ' + s.lastName,
      lastUpdated: s.lastUpdated || Date.now()
    };
  });
  return map;
}

module.exports = {
  getDefaultMasterData,
  getMasterDataStore,
  getStudentMasterRecord,
  saveStudentMasterRecord,
  getAllMasterStudentsList,
  getStaffProfilesMap
};
